### ISSUE TITLE
How to save tox data into encrypted file?

### ISSUE THREAD

**Issue by hackerkid** [saneki/node-toxcore#18]
I have been trying to save the tox instance with the help of `encryptFile(filepath, data, pass, callback)`. But I am getting error when trying to do this. Can you please provide an example?

**Comment by saneki** [comment]
Added a basic [crypto example](/saneki/node-toxcore/blob/master/examples/bin/crypto-example.js) in the examples directory.

For your specific use case, try something like:

``` js
var toxcore = require('toxcore');
var tox = new toxcore.Tox();
var crypto = new toxcore.ToxEncryptSave();

// ...

tox.getSavedata(function(err, data) {
  if (!err) {
    crypto.encryptFile('my_file.tox', data, 'my_passphrase', function(err) {
      if (!err) console.log('Success!');
      else console.error(err);
    });
  } else console.error(err);
});
```

**Comment by hackerkid** [comment]
Thank you for that quick reply :smiley:
