### ISSUE TITLE
License change (GPLv3)

### ISSUE THREAD

**Issue by saneki** [saneki/node-toxcore#5]
I'm planning on changing the license to GPLv3, which toxcore is licensed under anyways. I would like to request permission from @mensinda and @Arvius that they have no qualms with this change.

- [x] @saneki
- [x] @mensinda
- [x] @Arvius

**Comment by mensinda** [comment]
I have no problems with a license change to GPLv3.

**Comment by Arvius** [comment]
Yeah, i also don't see problems. Thanks for request. :)
